# Generated by Django 4.2.23 on 2025-07-12 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('age', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField(help_text='Height in cm')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('location', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(upload_to='profile_photos/')),
                ('interests', models.CharField(blank=True, max_length=255)),
                ('preferred_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both'), ('O', 'Other')], default='O', max_length=1)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=True)),
                ('preferred_age_min', models.PositiveIntegerField(default=18)),
                ('preferred_age_max', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
