# Generated by Django 4.2.23 on 2025-07-12 06:21

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='audio_bio',
            field=models.FileField(default='media/IMG_2466.JPG', upload_to='media/audio_player/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='media/IMG_2466.JPG', upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_links',
            field=models.JSONField(blank=True, default=profiles.models.Profile.contact_default),
        ),
    ]
